FROM hub.docker.vpclub.cn/vpclub/java:8
VOLUME /app 
ADD app/${app}-${ver}.jar /app/${app}-${ver}.jar
ENV PROFILE=${profile}
ENTRYPOINT ["java","-Xmx128m","-Xss256k","-jar","/app/${app}-${ver}.jar","-Dspring.profiles.active=$PROFILE"]
